### ISSUE TITLE
Again

### ISSUE THREAD

**Issue by Froscht** [GeoSaffer/ToAffinityAndBeyond#4]
To Affinity and Beyond (version 1.0.3)
Created by..........Grumpy

==============================================================================================================

64 bit OS: True

64 bit Process: True

Total Cores: 64

==============================================================================================================

Found -> D:/ARK/Servers/Server 8 Aberration/ShooterGame/Binaries/Win64/ShooterGameServer.exe v321.1,     ProcessID: 17144
The parameter is incorrect
 Found -> D:/ARK/Servers/Server 8 Aberration/ShooterGame/Binaries/Win64/ShooterGameServer.exe v321.1,    ProcessID: 17144
The parameter is incorrect

```
{
  "TimedInterval": 15,
  "ProcessTitleList": [
    {
      "Title": "Server 1 Ragnarok",
      "PreferedAffinity": [16,17,18,19]
    },
	{
      "Title": "Server 2 Extrinction",
      "PreferedAffinity": [20,21,22,23]
    },
	{
      "Title": "Server 3 The Island",
      "PreferedAffinity": [24,25,26,27]
    },
	{
      "Title": "Server 4 Scorched Earth",
      "PreferedAffinity": [28,29,30,31]
    },
	{
      "Title": "Server 5 Crystal Isles",
      "PreferedAffinity": [32,33,34,35]
    },
	{
      "Title": "Server 6 Genesis",
      "PreferedAffinity": [36,37,38,39]
    },{
      "Title": "Server 7 The Center",
      "PreferedAffinity": [40,41,42,43]
    },
	{
      "Title": "Server 8 Aberration",
      "PreferedAffinity": [44,45,46,47]
    },
	{
      "Title": "Server 9 Vulguero",
      "PreferedAffinity": [48,49,50,51]
    },
	{
      "Title": "Server 99 TestServer",
      "PreferedAffinity": [52,53,54,56]
    },
	{
      "Title": "Server 99+1 TESTSERVER 2",
      "PreferedAffinity": [57,58,59,60]
    }	
  ]
}
```

**Comment by GeoSaffer** [comment]
Please download the latest version ( 1.0.4 ) and try again, we have run and tested it on a 64 core Windows 2019 Server, and all should be working now.

**Comment by Froscht** [comment]
works now, can be closed Thank you
